### ISSUE TITLE
As a LevelBuilder user I want to place buckets so that I can make release levels

### ISSUE THREAD

**Issue by jkearisman** [wpics3733/SixesWild#6]

**Comment by tfinelli** [comment]
![image](https://cloud.githubusercontent.com/assets/11633621/7446699/6824209e-f1af-11e4-9594-a43bb8159abe.png)
I'll work on this.  This is a mock-up/draft of how I envision it.  If something looks off, let me know.

**Comment by djkiourtsis** [comment]
Sorry that I forgot to check here first, I already wrote code for the buckets in the LevelBuilder.

**Comment by tfinelli** [comment]
Ok, closing this then.
